In [49]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanupy

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [50]:
df.sample(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
399239,Data Scientist,Stagiaire Data scientist H/F,"Nanterre, France",via BeBee,Internship,False,France,2023-01-23 18:12:13,False,False,France,None,NaN,NaN,SERVIER MONDE,"['python', 'sql', 'jupyter', 'git', 'docker']","{'libraries': ['jupyter'], 'other': ['git', 'd..."
776752,Data Engineer,Data Warehouse Engineer,Anywhere,via LinkedIn,Contractor,True,"Illinois, United States",2023-11-19 05:06:00,False,False,United States,None,NaN,NaN,Allied OneSource,"['sql', 'sql server', 'azure', 'cognos', 'flow']","{'analyst_tools': ['cognos'], 'cloud': ['azure..."
2775,Data Engineer,Data Engineer F/H,"Lyon, France",via LinkedIn,Full-time,False,France,2023-02-27 13:23:17,False,False,France,None,NaN,NaN,evoteo,"['sql', 'python', 'scala', 'sql server', 'elas...","{'analyst_tools': ['ssrs'], 'cloud': ['databri..."

In [51]:
df.index.dtype #int64

df.index.name # No name for the idex is set (no title over index column)

In [52]:
df.index.name = 'job_index'

df.sample(3) # name is set

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
653978,Data Engineer,Data Engineer,"Ontario, Canada",via BeBee Canada,Full-time,False,Canada,2023-08-11 10:14:34,True,False,Canada,None,NaN,NaN,CanCap Group Inc.,"['sql', 'sql server', 'ssrs', 'ssis']","{'analyst_tools': ['ssrs', 'ssis'], 'databases..."
338072,Business Analyst,Business Support & Financial Control Analyst,"Doha, Qatar",via JobLeads,Full-time,False,Qatar,2023-04-18 23:45:35,False,False,Qatar,None,NaN,NaN,Qatar Airways Group,"['power bi', 'excel', 'word', 'ms access']","{'analyst_tools': ['power bi', 'excel', 'word'..."
405761,Senior Data Engineer,Senior Data Engineer,"North Chicago, IL",via Lensa,Full-time,False,Georgia,2023-09-02 17:21:07,False,False,United States,None,NaN,NaN,Motion Recruitment,"['python', 'sql', 'nosql', 'elasticsearch', 'a...","{'analyst_tools': ['splunk'], 'cloud': ['aws',..."

In [53]:
salary_stats = df.pivot_table(values= 'salary_year_avg', index= 'job_title_short', aggfunc= ['median', 'mean', 'max'])

salary_stats #index is already created with the column name

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  85000.0    91082.612833        387460.0
Cloud Engineer                    90000.0   111268.453846        280000.0
Data Analyst                      90000.0    93841.907854        650000.0
Data Engineer                    125000.0   130125.604250        525000.0
Data Scientist                   127500.0   135988.837171        960000.0
Machine Learning Engineer        106415.0   126774.315972        325000.0
Senior Data Analyst              111175.0   113911.363665        425000.0
Senior Data Engineer             147500.0   145840.611624        425000.0
Senior Data Scientist            155500.0   154206.292996        890000.0
Software Engineer                 99150.0   113393.760054        375000.0

In [54]:
salary_stats.index.name

'job_title_short'

In [55]:
df_in = df[df['job_country'] == 'India']

df_in.reset_index(inplace= True) # old index is set aside (kept) and new index takes palce

df_in.head(5) # The new index again won't have a name, job_index now becomes a column

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,16,Data Engineer,Big Data Engineer,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-06-15 13:28:03,False,False,India,None,NaN,NaN,Hexaware Technologies,"['powershell', 'python', 'sql', 'mysql', 'sql ...","{'cloud': ['databricks', 'azure'], 'databases'..."
1,19,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,2023-04-26 13:20:12,False,False,India,None,NaN,NaN,Bitwise Solutions,"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
2,29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,None,NaN,NaN,Exusia,None,None
3,38,Data Analyst,Data Quality and Governance Analyst 1,India,via Trabajo.org,Full-time,False,India,2023-07-23 13:24:57,False,False,India,None,NaN,NaN,"Jones Lang LaSalle IP, Inc","['sql', 'python', 'databricks', 'power bi', 'e...","{'analyst_tools': ['power bi', 'excel', 'word'..."
4,42,Senior Data Engineer,"Senior Data Engineer(Python)-1563,1637&1633","Chennai, Tamil Nadu, India",via HR Software For Growing Businesses | Fresh...,Full-time,False,India,2023-11-10 13:30:41,True,False,India,None,NaN,NaN,CESIT,"['python', 'sql', 'aws', 'pyspark', 'docker', ...","{'async': ['jira'], 'cloud': ['aws'], 'librari..."

In [56]:
salary_stats.reset_index(inplace= True) #here job_title_short is no longer the index

salary_stats

             job_title_short          median            mean             max
                             salary_year_avg salary_year_avg salary_year_avg
0           Business Analyst         85000.0    91082.612833        387460.0
1             Cloud Engineer         90000.0   111268.453846        280000.0
2               Data Analyst         90000.0    93841.907854        650000.0
3              Data Engineer        125000.0   130125.604250        525000.0
4             Data Scientist        127500.0   135988.837171        960000.0
5  Machine Learning Engineer        106415.0   126774.315972        325000.0
6        Senior Data Analyst        111175.0   113911.363665        425000.0
7       Senior Data Engineer        147500.0   145840.611624        425000.0
8      Senior Data Scientist        155500.0   154206.292996        890000.0
9          Software Engineer         99150.0   113393.760054        375000.0

In [57]:
df_in.set_index('job_index', inplace=True)  #can be only run ONCE; discard old index and used mention col(s) as new index

df_in #main difference between reset and set index is that set index discards the old index while reset one adds it as a col

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
16,Data Engineer,Big Data Engineer,"Pune, Maharashtra, India",via LinkedIn,Full-time,False,India,2023-06-15 13:28:03,False,False,India,None,NaN,NaN,Hexaware Technologies,"['powershell', 'python', 'sql', 'mysql', 'sql ...","{'cloud': ['databricks', 'azure'], 'databases'..."
19,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Indeed,Full-time,False,India,2023-04-26 13:20:12,False,False,India,None,NaN,NaN,Bitwise Solutions,"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['..."
29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,None,NaN,NaN,Exusia,None,None
38,Data Analyst,Data Quality and Governance Analyst 1,India,via Trabajo.org,Full-time,False,India,2023-07-23 13:24:57,False,False,India,None,NaN,NaN,"Jones Lang LaSalle IP, Inc","['sql', 'python', 'databricks', 'power bi', 'e...","{'analyst_tools': ['power bi', 'excel', 'word'..."
42,Senior Data Engineer,"Senior Data Engineer(Python)-1563,1637&1633","Chennai, Tamil Nadu, India",via HR Software For Growing Businesses | Fresh...,Full-time,False,India,2023-11-10 13:30:41,True,False,India,None,NaN,NaN,CESIT,"['python', 'sql', 'aws', 'pyspark', 'docker', ...","{'async': ['jira'], 'cloud': ['aws'], 'librari..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785712,Data Engineer,India - Collections Analyst II,India,melalui BeBee India,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Varite India Private Limited,"['excel', 'flow']","{'analyst_tools': ['excel'], 'other': ['flow']}"
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,None,NaN,NaN,Amul,None,None
785716,Software Engineer,Application Support Analyst,India,melalui BeBee India,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,CompuGroup Medical,"['c#', 'sql']","{'programming': ['c#', 'sql']}"
785718,Business Analyst,Senior Performance QA Analyst,India,melalui BeBee India,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,None,NaN,NaN,Diebold Nixdorf,None,None
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
salary_stats.set_index('job_title_short', inplace= True)

salary_stats

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  85000.0    91082.612833        387460.0
Cloud Engineer                    90000.0   111268.453846        280000.0
Data Analyst                      90000.0    93841.907854        650000.0
Data Engineer                    125000.0   130125.604250        525000.0
Data Scientist                   127500.0   135988.837171        960000.0
Machine Learning Engineer        106415.0   126774.315972        325000.0
Senior Data Analyst              111175.0   113911.363665        425000.0
Senior Data Engineer             147500.0   145840.611624        425000.0
Senior Data Scientist            155500.0   154206.292996        890000.0
Software Engineer                 99150.0   113393.760054        375000.0

In [ ]:
salary_stats.sort_values(by=('median', 'salary_year_avg'), ascending=False, inplace= True)

salary_stats #changing sort order for demonstration

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            155500.0   154206.292996        890000.0
Senior Data Engineer             147500.0   145840.611624        425000.0
Data Scientist                   127500.0   135988.837171        960000.0
Data Engineer                    125000.0   130125.604250        525000.0
Senior Data Analyst              111175.0   113911.363665        425000.0
Machine Learning Engineer        106415.0   126774.315972        325000.0
Software Engineer                 99150.0   113393.760054        375000.0
Cloud Engineer                    90000.0   111268.453846        280000.0
Data Analyst                      90000.0    93841.907854        650000.0
Business Analyst                  85000.0    91082.612833        387460.0

In [ ]:
salary_stats.sort_index() #sorts back the dataframe using the index alphabetically, useful when index doesn't have name

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  85000.0    91082.612833        387460.0
Cloud Engineer                    90000.0   111268.453846        280000.0
Data Analyst                      90000.0    93841.907854        650000.0
Data Engineer                    125000.0   130125.604250        525000.0
Data Scientist                   127500.0   135988.837171        960000.0
Machine Learning Engineer        106415.0   126774.315972        325000.0
Senior Data Analyst              111175.0   113911.363665        425000.0
Senior Data Engineer             147500.0   145840.611624        425000.0
Senior Data Scientist            155500.0   154206.292996        890000.0
Software Engineer                 99150.0   113393.760054        375000.0