In [34]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanupy

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [35]:
def inflation(salary):
    return salary * 1.03

df['salary_year_inflated'] = df['salary_year_avg'].apply(inflation)

df[pd.notna(df['salary_year_avg'])][['salary_year_avg', 'salary_year_inflated']] #Displaying only where fucntion is applied

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [36]:
df['salary_year_inflated'] = df['salary_year_avg'].apply(lambda salary: salary * 1.03) # Written simply with lambda

df[pd.notna(df['salary_year_avg'])][['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [37]:
# Projected Salary with Senior and Non_Senior roles

#def projected_salary(row):
 #   if 'Senior' in row['job_title_short']:
  #      return  1.05 * row['salary_year_avg']
   # else:
    #    return  1.03 * row['salary_year_avg']
    

df['salary_year_inflated'] = df.apply((lambda row: row['salary_year_avg'] * 1.05 if 'Senior' in row['job_title_short'] else row['salary_year_avg'] * 1.03), axis = 1)

In [38]:
df[pd.notna(df['salary_year_avg'])][['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]

In [39]:
# Converting the job skills col into a list

df.job_skills[1]

type(df.job_skills[1]) # currently in string

str

In [40]:
import ast

ast.literal_eval(df['job_skills'][2]) #converts string into list

['python',
 'sql',
 'c#',
 'azure',
 'airflow',
 'dax',
 'docker',
 'kubernetes',
 'jenkins']

In [41]:
# Applying the str to list conversrion to the entire column

df['job_skills'] = df['job_skills'].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else x) # Here only non-Nan values are changed or it would have thrown an error

In [43]:
df.job_skills[2] # Now each row in the job_skills col contains a list

['python',
 'sql',
 'c#',
 'azure',
 'airflow',
 'dax',
 'docker',
 'kubernetes',
 'jenkins']